**The problems in this assignment are sequential. There is no need to load finance_data or text_data from the CSV files for each question.**

In [53]:
import pandas as pd
# read finance data from csv
finance_data = pd.read_csv('./finance_data.csv')
# read text data from csv
text_data = pd.read_csv('./text_data.csv')

# look at the data sample
#finance_data.head()
text_data.head()

,ticker,year,quarter,total_word_count,neg,neu,pos,compound
0,SWKS,2022,q1,5408,0.013799,0.794847,0.191359,0.266350
1,CVS,2022,q1,7238,0.011254,0.823173,0.165576,0.294958
2,VNO,2022,q1,8400,0.014297,0.881848,0.103842,0.185106
3,BMY,2022,q1,8107,0.012447,0.816974,0.170585,0.266373
4,LVS,2022,q1,4458,0.021880,0.787235,0.190891,0.206733

**Question 1: If a row in finance_data has null sic_two_digit, that means the financial data could not be effectively extracted from the database. Write code to remove the rows in finance_data if sic_two_digit is null.**

In [ ]:
finance_data.dropna(subset=['sic_two_digit'], inplace = True)
print(finance_data)

**Question 2: After we describe the data, we notice that the revenue column has remaining null values. Write code to fill the null values in revenue with the average of non-null revenue values.**

In [58]:
finance_data["revenue"].fillna(finance_data['revenue'].mean())
print(finance_data)

   ticker  year quarter  sic_two_digit      sales    revenue  net_income  \
0     AAL  2022      q1           45.0   8899.000   8899.000   -1635.000
1     ADM  2022      q1           20.0  23650.000  23650.000    1054.000
2     ADP  2022      q1           73.0   3832.300   3832.300     700.500
3    ADSK  2022      q1           73.0   1170.000   1170.000     146.000
4     AIG  2022      q1           63.0  14966.000  14966.000    4173.000
..    ...   ...     ...            ...        ...        ...         ...
95    WFC  2022      q1           60.0  18688.000        NaN    3788.000
96    WRK  2022      q1           26.0   4952.200   4952.200     182.300
97    WST  2022      q1           30.0    720.000    720.000     173.800
98   WYNN  2022      q1           79.0    953.334    953.334    -183.324
99   ZION  2022      q1           60.0    697.000        NaN     203.000

    total_assets
0       67401.00
1       64866.00
2       59987.20
3        8261.00
4      573513.00
..           ...
95    1939709.00
96      29082.50
97       3294.70
98      12179.31
99      91126.00

[100 rows x 8 columns]

**Question 3: After further examination of the data, we find that there is a wrong entry in the ticker column. Write code to replace the ticker which equals 'BFB' to 'BF.B' in text_data.**

In [ ]:

text_data[text_data['ticker'] == 'BFB'] = "BF.B" # This corrects the ticker symbol for the corporation
text_data[text_data['ticker'] == 'BF.B'] # This shows the corrected ticker symbol

Empty DataFrame
Columns: [ticker, year, quarter, total_word_count, neg, neu, pos, compound]
Index: []

**Question 4: Write code to identify the row(s) in text_data whose ticker is not in finance_data.**

**Question 5: Write code to merge finance_data and text_data on three columns: ticker, year, and quarter. Name the merged DataFrame "merged_data".**

*Hint: If two rows in finance_data and text_data have equal values on all of the three fields (i.e., ticker, year, and quarter), we merge the rows.*

**Question 6: Write code to count the number of rows for each unique sic_two_digit in merged_data**

**Question 7: Add a new column labeled as industry to merged_data. If sic_two_digit is 36, industry equals 'Electronics'. If sic_two_digit is 28, industry equals 'Chemicals'. If sic_two_digit is 73, industry is 'Business Services'. For other sic_two_digit values, industry is 'Others'**

**Question 8: Write code to answer the following question: for each industry (i.e., Electronics, Chemicals, Business Services and Others), what is the average revenue and average total_word_count?**

**Question 9: Write code to answer the following question: what is the correlation between a company's return on asset and its compound sentiment score?**

*Hint: Return on asset is net income divided by total assets.*

**Question 10: Plot a scatter plot with return on asset and compound sentiment score on the x-axis and y-axis, respectively. Explain the pattern that you see in the plot.**